[tool.poetry]
name = "langchain-layer"
version = "1.4.4"
authors = [ "Amazon Web Services" ]
description = "Layer for LangChain libraries"
packages = [
    { include = "*.toml" },
    { include = "*.lock" },
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.26.4"
langchain = "0.2.5"
langchain-core = "0.2.7"
langchain-community = "0.2.5"
langchain-aws = "0.1.6"


[build-system]
requires = [ "poetry-core>=1.0.8" ]
build-backend = "poetry.core.masonry.api"